/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

/**
 *
 * @author Acer
 */
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksiDB;
import javafx.scene.control.RadioButton;
public class Anggota extends javax.swing.JFrame {
    private String sql;
    private PreparedStatement ps=null;
    public DefaultTableModel dtm;           //untuk kelamin (tbl klik mouse)
    /**
     * Creates new form Anggota
     */
    public Anggota() {
        initComponents();
         tampilkanDataAnggota();
        bersih();
        setLocationRelativeTo(this);
        rbLaki.setActionCommand("Laki-laki");
        rbPerempuan.setActionCommand("Perempuan");
    }

    
    private void tampilkanDataAnggota() {
        try {
            String sql="select * from tb_anggota";
            PreparedStatement ps=null;
            Object[]row={"Id Anggota","Nama","Kelas","Jenis Kelamin","No. Handphone","Alamat","Status"};
            DefaultTableModel dtm=new DefaultTableModel(null,row);
            TblAnggota.setModel(dtm);
            jScrollPane1.setEnabled(true);
            jScrollPane1.setBorder(null);
            jScrollPane1.setViewportView(TblAnggota);
            ResultSet rs=null;
            ps=koneksiDB.ambilkoneksidatabase().prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()) {
                String id=rs.getString(1);
                String nama=rs.getString(2);
                String kelas=rs.getString(3);
                String jk=rs.getString(4);
                String hp=rs.getString(5);
                String alamat=rs.getString(6);
                String status=rs.getString(7);
                String [] baris={id,nama,kelas,jk,hp,alamat,status};
                dtm.addRow(baris);
            }
        } catch (Exception e){}
    }
    
    private void bersih(){
        tfId.setText("");
        tfNama.setText("");
        tfKelas.setText("");
        kelamin.clearSelection();       //buttongroup
        tfTelp.setText("");
        tfAlamat.setText("");
        tfCariDataAnggota.setText("");
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(true);
        tfId.setEditable(true);
    }
    
    private void CariData() {
        try {
            String cari=tfCariDataAnggota.getText();
            String sql="select * from tb_anggota where id_anggota like'%"+cari+"%' or nama like'%"+cari+"%'";
            PreparedStatement ps=null;
            Object[]row={"Id Anggota","Nama","Kelas","Jenis Kelamin","No. Handphone","Alamat","Status"};
            DefaultTableModel dtm=new DefaultTableModel(null,row);
            TblAnggota.setModel(dtm);
            jScrollPane1.setEnabled(true);
            jScrollPane1.setBorder(null);
            jScrollPane1.setViewportView(TblAnggota);
            ResultSet rs=null;
            ps=koneksi.koneksiDB.ambilkoneksidatabase().prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()){
                String id=rs.getString(1);
                String nama=rs.getString(2);
                String kelas=rs.getString(3);
                String jk=rs.getString(4);
                String hp=rs.getString(5);
                String alamat=rs.getString(6);
                String status=rs.getString(7);
                String [] baris={id,nama,kelas,jk,hp,alamat,status};
                dtm.addRow(baris);
            }
            
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Data yang anda cari tidak dapat ditemukan !" +e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelamin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        tfKelas = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        tfTelp = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tfCariDataAnggota = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblAnggota = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, 20));

        tfId.setText("jTextField1");
        tfId.setBorder(null);
        getContentPane().add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 230, 10));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kelas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, 20));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Kelamin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 20));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. Handphone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, 20));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Id Anggota");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 20));

        tfNama.setText("jTextField1");
        tfNama.setBorder(null);
        getContentPane().add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 148, 230, 10));

        tfKelas.setText("jTextField1");
        tfKelas.setBorder(null);
        getContentPane().add(tfKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 220, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 230, 10));

        rbLaki.setBackground(new java.awt.Color(28, 42, 57));
        kelamin.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        rbLaki.setForeground(new java.awt.Color(255, 255, 255));
        rbLaki.setText("Laki-Laki");
        rbLaki.setBorder(null);
        rbLaki.setContentAreaFilled(false);
        rbLaki.setFocusPainted(false);
        getContentPane().add(rbLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, 20));

        rbPerempuan.setBackground(new java.awt.Color(28, 42, 57));
        kelamin.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        rbPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        rbPerempuan.setText("Perempuan");
        rbPerempuan.setBorder(null);
        rbPerempuan.setContentAreaFilled(false);
        rbPerempuan.setFocusPainted(false);
        getContentPane().add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 90, 20));

        tfTelp.setText("jTextField1");
        tfTelp.setBorder(null);
        getContentPane().add(tfTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 230, 20));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 240, 10));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, 20));

        tfAlamat.setText("jTextField1");
        tfAlamat.setBorder(null);
        getContentPane().add(tfAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 230, 20));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 240, 10));

        btnSave.setBackground(new java.awt.Color(153, 153, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 70, 30));

        btnEdit.setBackground(new java.awt.Color(255, 204, 51));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 70, 30));

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 70, 30));

        btnRefresh.setBackground(new java.awt.Color(0, 204, 0));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, 30));

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, 60, 30));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cari Data Anggota");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 130, 20));

        tfCariDataAnggota.setText("jTextField1");
        tfCariDataAnggota.setBorder(null);
        tfCariDataAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariDataAnggotaActionPerformed(evt);
            }
        });
        tfCariDataAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCariDataAnggotaKeyReleased(evt);
            }
        });
        getContentPane().add(tfCariDataAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 150, 20));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 150, 10));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/library.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 770, 40));

        TblAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        TblAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblAnggota);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 770, 140));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Data Anggota");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 170, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ddp-EX3gFC6eP4c-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1070, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            if ((tfId.getText().equals(""))
                || (tfNama.getText().equals(""))
                || (tfKelas.getText().equals(""))
                || (tfTelp.getText().equals(""))
                || (tfAlamat.getText().equals("")))
            {
                JOptionPane.showMessageDialog(rootPane, "Lengkapi data dengan benar terlebih dahulu");
            }
            else {
                
                String jk=null;
                if(rbLaki.isSelected()){
                    jk="Laki-laki";
                } else if (rbPerempuan.isSelected()){
                    jk="Perempuan";
                }
                
                try{
                    String sql = "INSERT INTO tb_anggota VALUES('"+ tfId.getText() +"','"+ tfNama.getText() +"','"+ tfKelas.getText() +"','"+ jk+"', '"+ tfTelp.getText() +"','"+ tfAlamat.getText() +"','Tidak pinjam')";
                ps=koneksi.koneksiDB.ambilkoneksidatabase().prepareStatement(sql);
                ps.executeUpdate(sql);
                {
                    JOptionPane.showMessageDialog(rootPane, "Data anda berhasil di simpan");
                }
                    tampilkanDataAnggota();
                    bersih();
                 }   catch (Exception e)
                        {
                           JOptionPane.showMessageDialog(rootPane, "Terjadi Kesalahan !");
                        }
         }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            String jk=null;
                if(rbLaki.isSelected()){
                    jk="Laki-laki";
                } else if (rbPerempuan.isSelected()){
                    jk="Perempuan";
                }
            String sql = "UPDATE tb_anggota SET nama='"+ tfNama.getText() +"', kelas='"+ tfKelas.getText() +"',jk='"+jk+"',telp='"+    tfTelp.getText() +"',alamat='"+ tfAlamat.getText() +"' WHERE id_anggota='"+ tfId.getText() +"'";
            ps=koneksi.koneksiDB.ambilkoneksidatabase().prepareStatement(sql);
            ps.executeUpdate(sql);
            {
                JOptionPane.showMessageDialog(rootPane, "Data berhasil di Edit !");
            }
            tampilkanDataAnggota();
            bersih();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data gagal di Edit");

        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
            try {
            int baris = TblAnggota.getSelectedRow();
            String stat = "Pinjam";
            int jawab;
            if(stat.equals(TblAnggota.getValueAt(baris, 6))){
                JOptionPane.showMessageDialog(null, "Tidak dapat menghapus selama dalam masa peminjaman");
//                reset();
            }else if((jawab = JOptionPane.showConfirmDialog(null,"Hapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
                sql = "DELETE FROM tb_anggota WHERE id_anggota='"+ tfId.getText() +"'";
                ps=koneksi.koneksiDB.ambilkoneksidatabase().prepareStatement(sql);
                ps.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Berhasil di hapus");
                bersih();
                tampilkanDataAnggota();
            }
            
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
            bersih();
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        tampilkanDataAnggota();
        bersih();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int keluar=JOptionPane.showConfirmDialog(rootPane, "Keluar Program?","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(keluar==JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void tfCariDataAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariDataAnggotaActionPerformed
        CariData();
    }//GEN-LAST:event_tfCariDataAnggotaActionPerformed

    private void TblAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblAnggotaMouseClicked
        // TODO add your handling code here:
         int baris = TblAnggota.getSelectedRow();
        tfId.setEditable(false);
        btnSave.setEnabled(false);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        kelamin.setSelected(null,false);
        tfId.setText(TblAnggota.getModel().getValueAt(baris, 0).toString());
        tfNama.setText(TblAnggota.getModel().getValueAt(baris, 1).toString());
        tfKelas.setText(TblAnggota.getModel().getValueAt(baris, 2).toString());
            if("Laki-laki".equals(TblAnggota.getModel().getValueAt(baris, 3).toString()))
                rbLaki.setSelected(true);
            else {
                rbPerempuan.setSelected(true);
            }
        tfTelp.setText(TblAnggota.getModel().getValueAt(baris, 4).toString());
        tfAlamat.setText(TblAnggota.getModel().getValueAt(baris, 5).toString());
    }//GEN-LAST:event_TblAnggotaMouseClicked

    private void tfCariDataAnggotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCariDataAnggotaKeyReleased
        CariData();
    }//GEN-LAST:event_tfCariDataAnggotaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblAnggota;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.ButtonGroup kelamin;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfCariDataAnggota;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfKelas;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTelp;
    // End of variables declaration//GEN-END:variables
}
