/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

/**
 *
 * @author Acer
 */
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksiDB;

public class Buku extends javax.swing.JFrame {
    private String sql;
    private PreparedStatement ps=null;
    /**
     * Creates new form Buku
     */
    public Buku() {
        initComponents();
        tampilkanDataBuku();
        bersih();
        setLocationRelativeTo(this);
    }

    
    private void tampilkanDataBuku() {
        try {
            String sql="select * from tb_buku";
            PreparedStatement ps=null;
            Object[]row={"Kode Buku","Judul Buku","Pengarang","Penerbit","Tahun Terbit","Kategori","Stok"};
            DefaultTableModel dtm=new DefaultTableModel(null,row);
            TblBuku.setModel(dtm);
            jScrollPane1.setEnabled(true);
            jScrollPane1.setBorder(null);
            jScrollPane1.setViewportView(TblBuku);
            ResultSet rs=null;
            ps=koneksiDB.ambilkoneksidatabase().prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()) {
                String kode=rs.getString(1);
                String judul=rs.getString(2);
                String pengarang=rs.getString(3);
                String penerbit=rs.getString(4);
                String tahun=rs.getString(5);
                String kategori=rs.getString(6);
                String stok=rs.getString(7);
                String [] baris={kode,judul,pengarang,penerbit,tahun,kategori,stok};
                dtm.addRow(baris);
            }
        } catch (Exception e){}
    }
    
    private void bersih(){
        tfKodeBuku.setText("");
        tfJudul.setText("");
        tfPengarang.setText("");
        tfPenerbit.setText("");
        tfTahun.setText("");
        cmbKategori.setSelectedItem("--Pilih--");
        tfStok.setText("");
        tfCariDataBuku.setText("");
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(true);
        tfKodeBuku.setEditable(true);
    }
    
    private void CariData() {
        try {
            String cari=tfCariDataBuku.getText();
            String sql="select * from tb_buku where kode_buku like'%"+cari+"%' or judul like'%"+cari+"%' or kategori like'%"+cari+"%'";
            PreparedStatement ps=null;
            Object[]row={"Kode Buku","Judul Buku","Pengarang","Penerbit","Tahun Terbit","Kategori","Stok"};
            DefaultTableModel dtm=new DefaultTableModel(null,row);
            TblBuku.setModel(dtm);
            jScrollPane1.setEnabled(true);
            jScrollPane1.setBorder(null);
            jScrollPane1.setViewportView(TblBuku);
            ResultSet rs=null;
            ps=koneksi.koneksiDB.ambilkoneksidatabase().prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()){
                String kode=rs.getString(1);
                String judul=rs.getString(2);
                String pengarang=rs.getString(3);
                String penerbit=rs.getString(4);
                String tahun=rs.getString(5);
                String kategori=rs.getString(6);
                String stok=rs.getString(7);
                String [] baris={kode,judul,pengarang,penerbit,tahun,kategori,stok};
                dtm.addRow(baris);
            }
            
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Data yang anda cari tidak dapat ditemukan !" +e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefresh = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        tfCariDataBuku = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblBuku = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfKodeBuku = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tfJudul = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        tfPengarang = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        tfPenerbit = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        tfTahun = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        cmbKategori = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        tfStok = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRefresh.setBackground(new java.awt.Color(0, 204, 0));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cari Data Buku");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 110, 20));

        tfCariDataBuku.setText("jTextField1");
        tfCariDataBuku.setBorder(null);
        tfCariDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariDataBukuActionPerformed(evt);
            }
        });
        tfCariDataBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCariDataBukuKeyReleased(evt);
            }
        });
        getContentPane().add(tfCariDataBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 150, 20));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 160, 10));

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 60, 30));

        TblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        TblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblBuku);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 730, 160));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setText("Kode Buku");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        tfKodeBuku.setText("jTextField1");
        tfKodeBuku.setBorder(null);
        jPanel1.add(tfKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, 10));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setText("Judul Buku");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 20));

        tfJudul.setText("jTextField1");
        tfJudul.setBorder(null);
        jPanel1.add(tfJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, 10));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel9.setText("Pengarang");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 20));

        tfPengarang.setText("jTextField1");
        tfPengarang.setBorder(null);
        jPanel1.add(tfPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 230, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 230, 10));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel10.setText("Penerbit");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        tfPenerbit.setText("jTextField1");
        tfPenerbit.setBorder(null);
        jPanel1.add(tfPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 230, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 230, 10));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel11.setText("Tahun Terbit");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 20));

        tfTahun.setText("jTextField1");
        tfTahun.setBorder(null);
        jPanel1.add(tfTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 230, 10));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel12.setText("Kategori");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 80, 20));

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Agama dan Filsafat", "Sejarah", "Novel", "Teknologi" }));
        jPanel1.add(cmbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 230, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel14.setText("Stock Buku");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 90, 20));

        tfStok.setText("jTextField1");
        tfStok.setBorder(null);
        jPanel1.add(tfStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 230, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 230, 10));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 70, 30));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 70, 30));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 260, 400));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Data Buku");
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/library.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 730, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bunga.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bunga.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 560, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int keluar=JOptionPane.showConfirmDialog(rootPane, "Keluar Program?","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(keluar==JOptionPane.YES_OPTION) {
                dispose();
            }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            sql="update tb_buku set judul= '"+tfJudul.getText()+
                    "',pengarang= '"+tfPengarang.getText()+
                    "',penerbit= '"+tfPenerbit.getText()+
                    "',tahun_terbit= '"+tfTahun.getText()+
                    "',kategori= '"+cmbKategori.getSelectedItem()+
                    "',stok_buku= '"+tfStok.getText()+
                    "' where kode_buku= '"+tfKodeBuku.getText()+"'";
            ps=koneksiDB.ambilkoneksidatabase().prepareStatement(sql);
            ps.executeUpdate();
            {
                JOptionPane.showMessageDialog(rootPane, "Data berhasil di Edit !");
            }
            tampilkanDataBuku();
            bersih();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data gagal di Edit"+e.getMessage());
            
            
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        PreparedStatement ps=null;
        String sql="insert into tb_buku values(?,?,?,?,?,?,?)";
        try {
            if ((tfKodeBuku.getText().equals(""))
            || (tfJudul.getText().equals(""))
            || (tfPengarang.getText().equals(""))
            || (tfPenerbit.getText().equals(""))
            || (tfTahun.getText().equals(""))        
            || (cmbKategori.getSelectedItem().equals(""))  
            || (tfStok.getText().equals("")))
            {
                JOptionPane.showMessageDialog(rootPane, "Lengkapi data dengan benar terlebih dahulu");
            }
            else {
                ps=koneksiDB.ambilkoneksidatabase().prepareStatement(sql);
                ps.setString(1, tfKodeBuku.getText());
                ps.setString(2, tfJudul.getText());
                ps.setString(3, tfPengarang.getText());
                ps.setString(4, tfPenerbit.getText());
                ps.setString(5, tfTahun.getText());
                ps.setString(6, (String) cmbKategori.getSelectedItem());
                ps.setString(7, tfStok.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data anda berhasil di simpan");
                tampilkanDataBuku();
                bersih();
            }
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Kode Buku ini sudah ada, Silahkan masukkan kode buku yang baru !");
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int jawab;
             if((jawab = JOptionPane.showConfirmDialog(null,"Hapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
            sql="delete from tb_buku where kode_buku= '"+tfKodeBuku.getText()+"'";
            ps=koneksi.koneksiDB.ambilkoneksidatabase().prepareStatement(sql);
            ps.executeUpdate(sql);
            {
                JOptionPane.showMessageDialog(rootPane, "Data Berhasil dihapus");
            }
            tampilkanDataBuku();
            bersih();
             }
        } catch (Exception e) {}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        tampilkanDataBuku();
        bersih();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tfCariDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariDataBukuActionPerformed

    }//GEN-LAST:event_tfCariDataBukuActionPerformed

    private void TblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblBukuMouseClicked
        // TODO add your handling code here:
        int row = TblBuku.getSelectedRow();
        tfKodeBuku.setText(TblBuku.getModel().getValueAt(row,0).toString());
        tfJudul.setText(TblBuku.getModel().getValueAt(row,1).toString());
        tfPengarang.setText(TblBuku.getModel().getValueAt(row,2).toString());
        tfPenerbit.setText(TblBuku.getModel().getValueAt(row,3).toString());
        tfTahun.setText(TblBuku.getModel().getValueAt(row,4).toString());
        cmbKategori.setSelectedItem(TblBuku.getModel().getValueAt(row,5).toString());
        tfStok.setText(TblBuku.getModel().getValueAt(row,6).toString());
        tfKodeBuku.setEditable(false);
        btnSave.setEnabled(false);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_TblBukuMouseClicked

    private void tfCariDataBukuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCariDataBukuKeyReleased
        // TODO add your handling code here:
        CariData(); 
    }//GEN-LAST:event_tfCariDataBukuKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblBuku;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField tfCariDataBuku;
    private javax.swing.JTextField tfJudul;
    private javax.swing.JTextField tfKodeBuku;
    private javax.swing.JTextField tfPenerbit;
    private javax.swing.JTextField tfPengarang;
    private javax.swing.JTextField tfStok;
    private javax.swing.JTextField tfTahun;
    // End of variables declaration//GEN-END:variables
}
